# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 20
  num_input_features: 16
  use_norm: True
  init_size: 32

###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk_multiscan" #  #  # "SemKITTI_sk" #
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/sematickitti/semantic-kitti_s20.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4

###################
## Data_loader options
train_data_loader:
  data_path: "/mnt/beegfs/gpu/argoverse-tracking-all-training/semantic-kitti/train_pseudo_20/sequences"
  #"/mnt/data/vras/data/gebreawe/semantic-kitti/dataset/sequences"
  #"/mnt/beegfs/gpu/argoverse-tracking-all-training/semantic-kitti/train_pseudo_20/sequences" #"/data/dataset/semantic_kitti/data_semkitti/dataset/sequences/"
  imageset: "train"
  return_ref: True
  batch_size: 3 #4
  shuffle: True
  num_workers: 4

val_data_loader:
  data_path: "/mnt/beegfs/gpu/argoverse-tracking-all-training/semantic-kitti/train_pseudo_20/sequences"
  #"/mnt/data/vras/data/gebreawe/semantic-kitti/dataset/sequences"
  #"/mnt/beegfs/gpu/argoverse-tracking-all-training/semantic-kitti/train_pseudo_20/sequences" #"/data/dataset/semantic_kitti/data_semkitti/dataset/sequences/"
  imageset: "val"
  return_ref: True
  batch_size: 3
  shuffle: False
  num_workers: 4
  
test_data_loader:
  data_path: "/mnt/beegfs/gpu/argoverse-tracking-all-training/semantic-kitti/train_pseudo_20/sequences"
  #"/mnt/data/vras/data/gebreawe/semantic-kitti/dataset/sequences"
  #"/mnt/beegfs/gpu/argoverse-tracking-all-training/semantic-kitti/train_pseudo_20/sequences" #"/data/dataset/semantic_kitti/data_semkitti/dataset/sequences/"
  imageset: "test"
  return_ref: True
  batch_size: 8
  shuffle: False
  num_workers: 0

ssl_data_loader:
  data_path: "/mnt/beegfs/gpu/argoverse-tracking-all-training/semantic-kitti/train_pseudo_20/sequences"
  #"/mnt/data/vras/data/gebreawe/semantic-kitti/dataset/sequences"
  #"/mnt/beegfs/gpu/argoverse-tracking-all-training/semantic-kitti/train_pseudo_20/sequences" #"/data/dataset/semantic_kitti/data_semkitti/dataset/sequences/"
  imageset: "ssl"
  return_ref: True
  batch_size: 8
  shuffle: False
  num_workers: 0

###################
## test params
train_params:
  model_load_path: "./model_save_dir/model_save_f3_3_s20_b3.pt"
  model_save_path: "./model_save_dir/model_save_f3_3_s20_b3.pt"
  checkpoint_every_n_steps: 1000
  max_num_epochs: 40
  eval_every_n_steps: 1000
  learning_rate: 0.001
  past: 3
  future: 3
  T_past: 3
  T_future: 3
  ssl: False
  rgb: False
